### ISSUE TITLE
Less sparse when applied to new dataset

### ISSUE THREAD

**Issue by bkj** [mfaruqui/sparse-coding#3]
I tried applying these algorithms to my own dataset, which consists of ~5K word embeddings (though they're constructed using a less standard method).  Using the same parameters, the results are far less sparse than when using the `glove` embeddings as described in the paper (50% compared to 90%).

Any ideas why this would be?  Perhaps the number of vectors has some effect (5K vs 400K)?  Some parameter needs tuning?

**Comment by mfaruqui** [comment]
You can try increasing the parameter value of the L1 regularisation. The more you will increase it, the sparser your vectors will become.
