### ISSUE TITLE
Compilation fails due for utils.cc (GCC 7.2.0, OS X Sierra)

### ISSUE THREAD

**Issue by sebastianpado** [mfaruqui/sparse-coding#4]
utils.cc:71:34: note:   'std::ifstream {aka std::basic_ifstream<char>}' is not derived from 'const Eigen::DenseBase<Derived>'
     cerr << "Could not open " << vec_file;

Solution: replace vec_file by vec_file_name (same: utils.cc:42).

**Comment by mfaruqui** [comment]
I made this change and pushed. Thanks Sebastian!
