### ISSUE TITLE
I'm confused

### ISSUE THREAD

**Issue by ASCII-ZJM** [mfaruqui/sparse-coding#6]
hello，I observed a critical question and that confused me when I meet the follewing code which locate on 198th~213th line of file "sparse-nonneg.cc":

#pragma omp parallel num_threads(cores) shared(total_error,atom_l1_norm)
#pragma omp for nowait private(word_id)
for (int word_id = 0; word_id < word_vecs.size(); ++word_id) {
/* Predict the i-th word and compute error */
Col pred_vec;
model.PredictVector(word_vecs[word_id], word_id, &pred_vec);
Col diff_vec = word_vecs[word_id] - pred_vec;
double error = diff_vec.squaredNorm();
#pragma omp critical
{
total_error += error;
num_words += 1;
atom_l1_norm += model.atom[word_id].var.lpNorm<1>();
cerr << num_words << "\r";
}
model.UpdateParams(word_id, RATE, diff_vec, l1_reg, l2_reg);
}
the variable model is shared between the threads ,so I think it should be settled in the omp critical region, can you explain it?
I'm from China, and I'm waiting for your answers

**Comment by mfaruqui** [comment]
Hi,
Yes, we have intentionally kept it out of opm critical region to make the code run faster. Many vector leaning approaches uses non-synchronous updates to the vectors. We did not find any substantial difference between quality of vectors with or without synchronous updates.

**Comment by ASCII-ZJM** [comment]
are you sure of that? I know that if keep it out of omp critical option can make the code run faster,but  settle the update operation out of omp critical region really have no effect on the final results?

**Comment by ASCII-ZJM** [comment]
are you sure of that? I know that if keep it out of omp critical option can make the code run faster,but settle the update operation out of omp critical region really have no effect on the final results?after all, there may be some threads use a semi-finished dictionary to do calculation.(I'm sorry, my English is poor☹)
